name: tests

on:
  push:
    paths:
      - '**/*.rs'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - '.github/workflows/tests.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**/*.rs'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - '.github/workflows/tests.yml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Install Rust toolchain"
        uses: dtolnay/rust-toolchain@master
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true

      - name: "Fmt check"
        run: cargo fmt --all -- --check

      - name: "Run tests"
        run: cargo test --all

      - name: "Run clippy"
        run: cargo clippy -- -D warnings -D clippy::pedantic --verbose --no-deps

      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
